version: "2"

services:
  api:
    restart: always
    build: ./api
    depends_on:
      - db
    ports:
      - 5000
    env_file:
      - .env
    environment:
      - SERVICE_PORTS=5000

  loadbalancer:
    image: 'dockercloud/haproxy:latest'
    links:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BALANCE=leastconn
    ports:
      - 80:80

  db:
    restart: always
    image: 'postgres:9.6.5'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data-postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

volumes:
  data-postgres:
